/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace HfiPayEscrow {
  export type PaymentStruct = {
    id: BigNumberish;
    sender: AddressLike;
    recipient: AddressLike;
    amount: BigNumberish;
    createdAt: BigNumberish;
    expiry: BigNumberish;
    claimed: boolean;
    refunded: boolean;
  };

  export type PaymentStructOutput = [
    id: bigint,
    sender: string,
    recipient: string,
    amount: bigint,
    createdAt: bigint,
    expiry: bigint,
    claimed: boolean,
    refunded: boolean
  ] & {
    id: bigint;
    sender: string;
    recipient: string;
    amount: bigint;
    createdAt: bigint;
    expiry: bigint;
    claimed: boolean;
    refunded: boolean;
  };
}

export interface HfiPayEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CLAIM_PERIOD"
      | "claimPayment"
      | "createPayment"
      | "getPayment"
      | "nextPaymentId"
      | "payments"
      | "refundPayment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PaymentClaimed"
      | "PaymentCreated"
      | "PaymentRefunded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CLAIM_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPayment",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPaymentId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refundPayment",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CLAIM_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextPaymentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundPayment",
    data: BytesLike
  ): Result;
}

export namespace PaymentClaimedEvent {
  export type InputTuple = [id: BigNumberish, recipient: AddressLike];
  export type OutputTuple = [id: bigint, recipient: string];
  export interface OutputObject {
    id: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    sender: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    sender: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    id: bigint;
    sender: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRefundedEvent {
  export type InputTuple = [id: BigNumberish, sender: AddressLike];
  export type OutputTuple = [id: bigint, sender: string];
  export interface OutputObject {
    id: bigint;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HfiPayEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): HfiPayEscrow;
  waitForDeployment(): Promise<this>;

  interface: HfiPayEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CLAIM_PERIOD: TypedContractMethod<[], [bigint], "view">;

  claimPayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createPayment: TypedContractMethod<
    [recipient: AddressLike],
    [void],
    "payable"
  >;

  getPayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [HfiPayEscrow.PaymentStructOutput],
    "view"
  >;

  nextPaymentId: TypedContractMethod<[], [bigint], "view">;

  payments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, boolean, boolean] & {
        id: bigint;
        sender: string;
        recipient: string;
        amount: bigint;
        createdAt: bigint;
        expiry: bigint;
        claimed: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;

  refundPayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CLAIM_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimPayment"
  ): TypedContractMethod<[paymentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createPayment"
  ): TypedContractMethod<[recipient: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [paymentId: BigNumberish],
    [HfiPayEscrow.PaymentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextPaymentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, boolean, boolean] & {
        id: bigint;
        sender: string;
        recipient: string;
        amount: bigint;
        createdAt: bigint;
        expiry: bigint;
        claimed: boolean;
        refunded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "refundPayment"
  ): TypedContractMethod<[paymentId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "PaymentClaimed"
  ): TypedContractEvent<
    PaymentClaimedEvent.InputTuple,
    PaymentClaimedEvent.OutputTuple,
    PaymentClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCreated"
  ): TypedContractEvent<
    PaymentCreatedEvent.InputTuple,
    PaymentCreatedEvent.OutputTuple,
    PaymentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRefunded"
  ): TypedContractEvent<
    PaymentRefundedEvent.InputTuple,
    PaymentRefundedEvent.OutputTuple,
    PaymentRefundedEvent.OutputObject
  >;

  filters: {
    "PaymentClaimed(uint256,address)": TypedContractEvent<
      PaymentClaimedEvent.InputTuple,
      PaymentClaimedEvent.OutputTuple,
      PaymentClaimedEvent.OutputObject
    >;
    PaymentClaimed: TypedContractEvent<
      PaymentClaimedEvent.InputTuple,
      PaymentClaimedEvent.OutputTuple,
      PaymentClaimedEvent.OutputObject
    >;

    "PaymentCreated(uint256,address,address,uint256)": TypedContractEvent<
      PaymentCreatedEvent.InputTuple,
      PaymentCreatedEvent.OutputTuple,
      PaymentCreatedEvent.OutputObject
    >;
    PaymentCreated: TypedContractEvent<
      PaymentCreatedEvent.InputTuple,
      PaymentCreatedEvent.OutputTuple,
      PaymentCreatedEvent.OutputObject
    >;

    "PaymentRefunded(uint256,address)": TypedContractEvent<
      PaymentRefundedEvent.InputTuple,
      PaymentRefundedEvent.OutputTuple,
      PaymentRefundedEvent.OutputObject
    >;
    PaymentRefunded: TypedContractEvent<
      PaymentRefundedEvent.InputTuple,
      PaymentRefundedEvent.OutputTuple,
      PaymentRefundedEvent.OutputObject
    >;
  };
}
